version: "3"
services:
  app:
    container_name: housing
    restart: always
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - "8000:8000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
